apiVersion: v1
kind: Pod
metadata:
    name: qos-besteffort
    namespace: cka-practice
spec:
  containers:
  - image: busybox
    name: qos-effort
    command: ["sh", "-c"]
    args: ["sleep 3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
