apiVersion: v1
kind: Pod
metadata:
  labels:
    run: app-pod
  name: app-pod
  namespace: cka-storage
spec:
  volumes:
  - name: mypd
    persistentVolumeClaim:
      claimName: pvc-share
  containers:
  - image: busybox
    name: app-pod
    command: ["sh", "-c", "echo hello > /data/hello.txt; ls -l /data; sleep 3600"]
    resources: {}
    volumeMounts:
    - name: mypd
      mountPath: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
