apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-share
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /exports/k8s-share
    server: 192.168.1.10
