apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-share
  namespace: cka-storage
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
     
