apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: database
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data
