apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-pod
    app: web
  name: web-pod
  namespace: cka-practice
spec:
  containers:
  - image: nginx:1.25
    name: web-pod
    ports:
    - containerPort: 80
    env:
     - name: ENV
       value: prod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
