apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hostpath-pvc-pod
  name: hostpath-pvc-pod
  namespace: cka-practice
spec:
  containers:
  - image: busybox
    name: hostpath-pvc-pod
    command: ['sh', '-c', 'while true; do date >> /var/log/app.log; sleep 5; done']
    volumeMounts:
    - mountPath: "/var/log"
      name: log-volume
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule" 
  nodeSelector:
    kubernetes.io/hostname: cka-practice-control-plane
  volumes:
    - name: log-volume
      persistentVolumeClaim:
        claimName: hostpath-pvc
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
