apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hostpath-vol-pod
  name: hostpath-vol-pod
  namespace: cka-practice
spec:
  containers:
  - image: busybox
    name: hostpath-vol-pod
    resources: {}
    command: ['sh', '-c', 'while true; do date >> /data/app.log; sleep 5; done']
    volumeMounts:
    - mountPath: /data
      name: host-path-volume
  nodeSelector:
    kubernetes.io/hostname: cka-practice-control-plane
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  volumes:
  - name: host-path-volume
    hostPath:
      path: /data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
