apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nfs-server
  name: nfs-server
  namespace: cka-practice
spec:
  containers:
  - image: itsthenetwork/nfs-server-alpine:latest
    name: nfs-server
    securityContext:
      privileged: true
    envFrom:
      - configMapRef:
          name: nfs-server
    volumeMounts:
    - mountPath: /nfs-data
      name: host-nfs-data
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: "Exists"
    effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: cka-practice-control-plane
  volumes:
  - name: host-nfs-data
    hostPath:
      path: /nfs-data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
