apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-hostpath-pv
spec:
  capacity: 
    storage: 10Gi
  accessModes: 
  - ReadWriteMany
  storageClassName: nfs-large
  hostPath:
    path: /nfs-data
