apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web-svc-pod
  name: web-svc-pod
  namespace: cka-practice
spec:
  containers:
  - image: nginx
    name: web-svc-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
