apiVersion: v1
kind: Pod
metadata:
  labels:
    name: web-service-cka
  name: web-service-pod
  namespace: cka-practice
spec:
  containers:
  - image: nginx
    name: web-service-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
