apiVersion: v1
kind: Pod
metadata:
    name: crashing-pod
    namespace: cka-practice
spec:
    containers:
    - name: crashing-pod
      image: busybox
      command: ["sh", "-c", "sleep 3600"] 
    restartPolicy: Always