apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ready-pod
  name: ready-pod
  namespace: cka-practice
spec:
  containers:
  - image: nginx
    name: ready-pod
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10  
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
