apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sidecar-pod
  name: sidecar-pod
  namespace: cka-practice-test-1
spec:
  containers:
  - image: busybox
    name: app
    command: ['sh', '-c', 'while true; do date >> /var/log/app.log; sleep 5; done']
    volumeMounts:
    - mountPath: /var/log
      name: logvolume
  - image: busybox
    name: sidecar
    command: ['sh', '-c', 'tail -f /var/log/app.log']
    volumeMounts:
    - mountPath: /var/log
      name: logvolume
  volumes:
  - name: logvolume
    emptyDir:
     sizeLimit: 200Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
