apiVersion: v1
kind: Pod
metadata:
  labels:
    run: qos-best-effort
  name: qos-best-effort
  namespace: cka-practice-test-1
spec:
  containers:
  - image: busybox
    name: qos-best-effort
    command: ["sh", "-c", "sleep 3600"]
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
