apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-vol-pod
  name: secret-vol-pod
  namespace: cka-practice-test-1
spec:
  containers:
  - image: nginx
    name: secret-vol-pod
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
    resources: {}
  volumes:
  - name: secret-volume
    secret:
      secretName: db-secret  
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
