apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web
  name: web-pod
  namespace: cka-practice-test-1
spec:
  containers:
  - image: nginx:1.25
    name: web-pod
    env:
    - name: ENV
      value: prod
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
