apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cm-env-pod
  name: cm-env-pod
  namespace: cka-practice
spec:
  containers:
  - image: busybox
    name: cm-env-pod
    command: ["sh", "-c", "echo $MODE; sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-config
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

