apiVersion: v1
kind: Pod
metadata:
    namespace: cka-practice
    name: cm-vol-pod
spec:
    containers:
      -  image: busybox
         name: cm-vol-pod
         command: ["sh", "-c", "cat /etc/config/MODE; sleep 3600"]
         volumeMounts:
         -  name: configvol
            mountPath: "/etc/config"
    volumes:
    - name: configvol
      configMap:
        name: app-config
    
       
    
    