apiVersion: v1
kind: Pod
metadata:
  labels:
  name: secret-valuefrom
  namespace: cka-practice
spec:
  containers:
  - image: busybox:latest
    name: secret-valuefrom
    command: ["sleep"]
    args:
    - "3600"
    env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
    - name: USER_NAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
