apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-vol-pod
  name: secret-vol-pod
  namespace: cka-practice
spec:
  containers:
  - image: busybox
    name: secret-vol-pod
    command: ["sleep"]
    args:
    - "3600"
    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret
        readOnly: True
  volumes:
    - name: secret-volume
      secret:
        secretName: db-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
