apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
  namespace: cka-practice
spec:
  containers:
  - image: busybox:latest
    name: secret-env-pod
    command: ["sleep"]
    args:
    - "3600"
    envFrom:
    - secretRef:
        name: db-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
