apiVersion: v1
kind: Service
metadata:
  labels:
    app: echosvc
  name: echo-svc
  namespace: echo-sound
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: echoserver-deployment
  type: ClusterIP
status:
  loadBalancer: {}
