apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Mi
  storageClassName: hostpath
