apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-data-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
