apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data-pv
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/nfs-data"
